### ISSUE TITLE
lottery: replace "user can" screenshot

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/tools.onout.org#1]
https://screenshots.wpmix.net/chrome_HxURYNKdFGkLutMjpbBDyhfEhYglnORj.png
лучше будет:
https://screenshots.wpmix.net/chrome_mdudDljnCr9EBgKzeY3NwRlpyWDvQpFq.png

**Comment by VitaliyShulik** [comment]
@noxonsu весь фрейм заменить одним простым скриншотом?

**Comment by VitaliyShulik** [comment]
https://github.com/noxonsu/tools.onout.org/commit/ac35195488b9c9332525481f78a7561c2d33ea40
