### ISSUE TITLE
add security warning and cloud version 

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/tools.onout.org#14]
на вп версиях добавить security warning 

Risk notification:  Our code is based on top audited sources, but our changes are unaudited from 3rd party auditors. We improve security but a lot of things are out of our control, for example, 3rd party software like WordPress, your server's software, your hosting provider. We have delivered dapps for hundreds of clients which handle tens of thousands of users. For the past 3 years, we have received about 10 incident reports kind of "a user lost funds".  Unfortunately, not all of them have been resolved. Ask yourself who other than you can access your server? When was your last time installing security updates?  The most secure choice would be our cloud solution (with a "revenue-share" payment model). For standalone versions please use as less plugins as you can and the "Simply Static plugin" and "Wodefence" for security.

**Comment by NotEternal** [comment]
в виде чего. При заходе в модальном окне показывать?

**Comment by noxonsu** [comment]
хз, пока надо подумать, плюс нужно описание cloud сделать чтоб ссылка была
