### ISSUE TITLE
add link to documentation everywhere

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/tools.onout.org#16]
![](https://screenshots.wpmix.net/Discord_kvmKeDatfuSWXqkAGWG1X7RK1ckM4vsb.png) 

чел говорит, что вообще не нашел документацию нигде. нужно добавить ссылки на kb повыше в каждое описание на лендосах на сайте и на cc и на ютубе

**Comment by noxonsu** [comment]
тут я вынес в шапку ссылки, помойму аккуратно и не отвлекает https://codecanyon.net/item/dao-factory-governance-and-proposals-plugin-for-your-token-for-wordpress/35608699

**Comment by noxonsu** [comment]
для сайта вынес в отдельную ишью https://github.com/noxonsu/tools.onout.org/issues/18

**Comment by VitaliyShulik** [comment]
Вроде везде добавил... кроме сайта.
