### ISSUE TITLE
access dashboard using web3

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/tools.onout.org#2]
разработать систему логина по метамаску и валетконнекту. дб не использовать (либо блокчейн), при логине на бэке проверять знаком ли нам этот человек https://docs.sendgrid.com/api-reference/contacts/search-contacts , если нет, то запрашивать емейл и две галки. 

- email me news about your products
- I am also interested in investment opportunities such as launchpads, farming, etc...

контакт добавлять в сенгрид записывая информацию о емейле, адресе метамаска (по которому потом и искать), отмеченые галочки, страна город https://www.npmjs.com/package/geoip-lite . проверить чтоб логинилось если бэк в дауне.

после логина уже показывать ссылки на покупку продуктов на лендосах (до этого вместо ссылки buy plugind показывать Get started)

**Comment by VitaliyShulik** [comment]
Здесь нужно микросервис делать как минимум для того чтобы запрос по проверке знаком ли нам этот человек (так как там используется SENDGRID_API_KEY, по которому как я понял все взаимодействия с API устроенны...)

**Comment by noxonsu** [comment]
делаем микросервис я про это и говорю
