### ISSUE TITLE
add promocode

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/tools.onout.org#24]
у нас есть партнеры которые хотят продавать наши продукты, для того, чтоб понять какой партнер привел клиента и что тот купил, нужно ввести промокоды. при начале оплаты должен быть окно ввода промокода, если введен промокод, то человеку предоставляется скидка 50 баксов примерно. подходит любой набор A-Z символов 5ть букв. промокод так же передавать в данных о платеже + передавать какой конкретно проудкт куплен в виде айди (1,2,3,4,5,6)

**Comment by NotEternal** [comment]
По хорошему надо их обнулят после использования, а то будет один вечный у всех. Значит надо хранить где то их с данными кто и когда использовал. Значит где то бд делать, или зашифровывать в блокчейне.
Или просто забить на это )

**Comment by noxonsu** [comment]
промокоды пусть используют сколько хотят, суть промокода идентифицировать кто привел клиента
