### ISSUE TITLE
add chat an links to all pages

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/tools.onout.org#5]
- [x] чтоб клиенты могли в сапорт написать 
```
<!-- FreeScout BEGIN -->
<script>var FreeScoutW={s:{"color":"#0068bd","position":"br","id":3882717100}};(function(d,e,s){if(d.getElementById("freescout-w"))return;a=d.createElement(e);m=d.getElementsByTagName(e)[0];a.async=1;a.id="freescout-w";a.src=s;m.parentNode.insertBefore(a, m)})(document,"script","https://support.onout.org/modules/chat/js/widget.js?v=2399");</script>
<!-- FreeScout END -->
```
- [x] проверить перелинковку страни и все ссылки buy заменить на get started (ведут на dash…)
- [x] ссылки из каталга должны вести на внутренние, не на кк.

**Comment by VitaliyShulik** [comment]
@noxonsu `ссылки из каталга должны вести на внутренние, не на кк.` - получается только у farm factory and mcwallet нет лендингов...
