### ISSUE TITLE
wrong links on contributon

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/tools.onout.org#52]
https://github.com/noxonsu/tools.onout.org/blob/main/doc/contributing.md#%D1%8D%D1%82%D0%B0%D0%BF-3---%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0-%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D0%B0-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA 

кликаю на ссылку "здесь" и попадаю на 404

**Comment by VitaliyShulik** [comment]
Looks solved
