### ISSUE TITLE
Update products list

### ISSUE THREAD

**Issue by NotEternal** [noxonsu/tools.onout.org#8]
Also change for Unifactory:
`0.05%-1% each trade` -> `0.01%-99% each trade`
> actually we cannot use each percent, but let's simplify this range

`Logo, colors, list of assets, fee address, admin address` -> `Logo, colors, list of assets, links, fee percent, admin and fee addresses`

![puifg123](https://user-images.githubusercontent.com/61930014/152116426-6011c9dd-6720-4722-ae83-e2d24b2ef56b.png)

**Comment by noxonsu** [comment]
Внеси изменения в index.html плиз
