### ISSUE TITLE
Typos/grammar issues on home page

### ISSUE THREAD

**Issue by Raccoonrider** [noxonsu/tools.onout.org#82]
Сразу 2 опечатки: sned => send, fok => fork.
По грамматике тоже не всё в порядке, я бы написал 
> **To** request **a** copy, **send** us a link to **the** project you like and we will research **if it is** possible to **fork**

![image](https://user-images.githubusercontent.com/92844006/188548208-11a2b1ad-10b6-42cb-a5c2-a31aa8148252.png)

**Comment by NotEternal** [comment]
#81
