### ISSUE TITLE
Create a base payment template and saving data

### ISSUE THREAD

**Issue by NotEternal** [noxonsu/tools.onout.org#9]

**Comment by noxonsu** [comment]
1. Чел логинится (емейл спрашиваемся - это сделано)
2. Видит список продуктов например dex.
3. Переходит в него, есть описание далее жмёт купить за 1000 usdt (к примеру)
4. После оплаты на вкладке «мои продукты» видит купленный продукт и ссылку на скачку, документацию, видосы
